# filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
# Training config
training:
  epochs: 200
  batch_size: 6
  num_workers: 4
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  task: sep_noisy
  train_dir: LibriMix/Libri3Mix/wav16k/min/train-360/meta/
  valid_dir: LibriMix/Libri3Mix/wav16k/min/dev/meta/
  sample_rate: 16000
  n_src: 2
  segment: 0.5